title: 535's Digital Den
email: ben.blank@gmail.com
github_username: benblank
url: https://five35.com/

# So that jekyll-seo-tag doesn't include the ginormous description below in the
# page title. 😱
tagline: My Home on the Internet

# I modified _includes/footer.html to treat the description as Markdown.
# However, it seems to normalize the whitespace first (or something), so it
# needs explicit line breaks.
description: >-
  As you can see, there isn't much here, yet. I'll be adding more content as I
  create it. And yes, I know "Digital Den" is a *terrible* name. Hopefully, I'll
  come up with something better, soon.
  <br><br>
  In the mean time, do you want to check out my poorly-maintained set of [user
  scripts](user-scripts/)? No? Okay, then.

markdown: kramdown
plugins:
  - jekyll-feed

# This is the "Minima 3.0" theme, which hasn't been published as a gem.
remote_theme: jekyll/minima

include:
  - .well-known
  - avatars
